### ISSUE TITLE
Gateway 

### ISSUE THREAD

**Issue by udaikumar59** [ttn-zh/ic880a-gateway#26] opened 2017-10-27 08:36 UTC
Hi,
we are setting up a lora gateway and we followed the same steps mentioned in https://github.com/ttn-zh/ic880a-gateway. but we are unable to find complete procedure to run the gateway connected to thethings network. we will be glad to help us in resolving the issue.
Thanks in Advance!
Regards

**Comment by gonzalocasas** [comment] 2017-10-27 10:11
Please describe the error otherwise it's hard to say what didn't work

**Comment by udaikumar59** [comment] 2017-10-30 07:53
hi

Thanks for your reply. We had tried with all the possibilities to start the concentrator but another important thing is that our gateway status is shown connected and packets are transmitted from the node also received at the ttn. We just viewed the data by integrating the cayenne LLP and registered the devices in  mydevices website.

Attached log file 

when we started the device again after 2 days, now the device is not connecting to ttn which means the ttn shows that gateway is not connected. attached a screenshot of this also with the log file of sudo tail -f /var/log/syslog and service ttn-gateway status

elektroniklab logo for Signature (2)

Thanks and regards ,

T .udhaya Kumar GM ( Tecchnical )

elektroniklab pvt ltd 

10 A , Masilamani street,  T.Nagar, Chennai - 600017

Ph:91 44 24336953 Fax :91 4424322819  mobile : 91 9840613199

Skype : udai.kumar1 - web : www.elektroniklab.com <http://www.elektroniklab.com/>

**Comment by gonzalocasas** [comment] 2017-10-30 10:21
If it was working and it started failing with `INFO: [main] Starting the concentrator - ERROR: [main] failed to start the concentrator` then something like the power supply might be faulty. Try replacing your PSU, making sure it's delivering stable output.

**Comment by udaikumar59** [comment] 2017-10-30 11:06
Thanks and lot will get back after trying 



Sent from Samsung tablet

-------- Original message --------

**Comment by udaikumar59** [comment] 2017-11-01 07:31
Hi

 

Thanks for the help , we changed the PSU & still the issue “failed to start the concentrator “ persists in the system. However the ttn network shows the connected status.

 

These are the problems, we found out in the system,

 

1.On a fresh day start, the ttn network shows connected status but last connected shows the previously connected time interval. So on every fresh day start, we reset the concentrator and make it live

2. There is some issue in lgw_connect() & lgw_hal_success() and that’s why the problem still persists.

3. when we run the test_loragw_hal() function it results “Impossible to start the concentrator”

4. when we tested test_loragw_spi(), it shows data received=48.

5. The data sent through program is ELAB and those data is not been received at the ttn end as payload.

6.Some raw data is been transmitted to the end on previous connect to ttn. Please let us know how to decrypt the data.

7.how to make the node to transmit the data or how to make the concentrator to receive the data. 

 

I followed https://github.com/matthijskooijman/arduino-lmic this page to makeup the node and even it shows these status

 

Starting…

Packet queued

178975: EV_TX COMPLETE (Waiting for RX Window)

Packet queued

 

8. Do we need to setup the pin configuration as per SX1301 PIN Configuration  given in https://github.com/Lora-net/lora_gateway/wiki/SX1301-GPIO-output-configuration

9. Pin configuration of imst and rpi as we connected in our style

 

Imst       rpi

13                                                           Reset                                                                                                    11


14

SPI CLK

23


15

MISO

21


16

MOSI

19


17

NSS

24

 

Attached log file. Please help us to resolve these issue. 

elektroniklab logo for Signature (2)

Thanks and regards ,

T .udhaya Kumar GM ( Tecchnical )

elektroniklab pvt ltd 

10 A , Masilamani street,  T.Nagar, Chennai - 600017

Ph:91 44 24336953 Fax :91 4424322819  mobile : 91 9840613199

Skype : udai.kumar1 - web : www.elektroniklab.com <http://www.elektroniklab.com/>

**Comment by gonzalocasas** [comment] 2018-02-04 17:10
This issue is very confusingly mixing gateway and node issues. I will close it because I've retested the gateway installation and it works fine, so, the issue is not related to this software repository (it could be hardware, or other environmental condition).

**Closed as completed by gonzalocasas** 2018-02-04 17:10 UTC
